server:
  host: "0.0.0.0"
  port: 8080
  debug: true
  version: "0.0.1"
  title: "Job Search Service"
  server_auth:
    secret: "secret"
    exp_time: 1
    algorithm: "HS256"

database:
  host: "db"
  port: 5432
  db: postgres
  user: postgres
  password: postgres